### ISSUE TITLE
Doesn't work with Safari Private Window

### ISSUE THREAD

**Issue by jason-nabooki** [vitr/safari-cookie-in-iframe#8]
Safari - Version 13.0.4 (15608.4.9.1.3)

When using the demo in Safari Private Window you get the error "Too bad :( No cookies for framed sites :("

http://vitr.github.io/safari-cookie-in-iframe/demo.html

**Comment by vitr** [comment]
but in private windows/sessions you don't have any cookies at all, isn't it the purpose of private browsing?!

**Comment by jason-nabooki** [comment]
Well not exactly. You still have cookies. They will just be cleared when you exit.

**Comment by vitr** [comment]
even with this in mind, you have 2 completely isolated private sessions: for the main and framed sites, I don't see how you can overcome this.
Appreciate any solution/pr though.

**Comment by jason-nabooki** [comment]
Ahhhh. Yep you're right. It looks like Safari private mode is different to other browsers where each tab/window appears to be sandboxed/isolated from each other.

In Chrome Incognito I can log into a website in one tab, then in another tab go to that same website and I'll still be logged in. Not the case with Safari.

As a result the workaround this repo provides will never work. Bummer :(
